name: deploy to Firebase

on:
  push:
    branches:
      - 'main'
    paths:
      - *

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: '${{ secrets.PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
      - run: npm install -g firebase-tools
      - run: npm ci
      - run: npm run build
      - run: firebase deploy
