name: Linter

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v18.x
      - run: npm ci
      - run: npm run lint -s